//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string IntegradorWebService_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["IntegradorWebService_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vipp.visualset.com.br")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "k9ic2VydmFjYW8xPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5RdWFudGlkYWRlPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xMTwvQ29sdW5hPjxUY" +
            "W1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q29udGV1ZG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjEwP" +
            "C9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pb" +
            "GhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5PYnNlcnZhY2FvMjwvTm9tZUF0cmlid" +
            "XRvPjxDb2x1bmE+MTM8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkRlc3RpbmF0Y" +
            "XJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTU8L0NvbHVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZ" +
            "WxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0c" +
            "mlidXRvPkRvY3VtZW50b0Rlc3RpbmF0YXJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTY8L0NvbHVuY" +
            "T48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PENvbHVuY" +
            "T4xNzwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+TnVtZXJvPC9Ob21lQXRyaWJ1d" +
            "G8+PENvbHVuYT4xODwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZG9yLz48L0Zvc" +
            "m1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+QmFpcnJvPC9Ob" +
            "21lQXRyaWJ1dG8+PENvbHVuYT4xOTwvQ29sdW5hPjxUYW1hbmhvPjA8L1RhbWFuaG8+PERlbGltaXRhZ" +
            "G9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q" +
            "29tcGxlbWVudG88L05vbWVBdHJpYnV0bz48Q29sdW5hPjIwPC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "E5vbWVBdHJpYnV0bz5DRVA8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIxPC9Db2x1bmE+PFRhbWFuaG8+M" +
            "DwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhb" +
            "mlsaGE+PE5vbWVBdHJpYnV0bz5DaWRhZGU8L05vbWVBdHJpYnV0bz48Q29sdW5hPjIyPC9Db2x1bmE+P" +
            "FRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtY" +
            "XRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5VRjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MjM8L0Nvb" +
            "HVuYT48VGFtYW5obz4wPC9UYW1hbmhvPjxEZWxpbWl0YWRvci8+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "EZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlNlcnZpY288L05vbWVBdHJpYnV0bz48Q29sd" +
            "W5hPjI1PC9Db2x1bmE+PFRhbWFuaG8+MDwvVGFtYW5obz48RGVsaW1pdGFkb3IvPjwvRm9ybWF0YWNhb" +
            "1BsYW5pbGhhPjwvQXJyYXlPZkZvcm1hdGFjYW9QbGFuaWxoYT4=")]
        public string LayoutCengage {
            get {
                return ((string)(this["LayoutCengage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFile {
            get {
                return ((string)(this["SaveFile"]));
            }
            set {
                this["SaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "klkZW50aWZpY2Fkb3I8L05vbWVBdHJpYnV0bz48Q29sdW5hPjE8L0NvbHVuYT48SW5pY2lvPjE8L0lua" +
            "WNpbz48VGFtYW5obz4zPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hd" +
            "GFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+TnJOb3RhRmlzY2FsP" +
            "C9Ob21lQXRyaWJ1dG8+PENvbHVuYT4yPC9Db2x1bmE+PEluaWNpbz41PC9JbmljaW8+PFRhbWFuaG8+N" +
            "zwvVGFtYW5obz48SW5pY2lvPjA8L0luaWNpbz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb" +
            "3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlNlcmllTm90Y" +
            "UZpc2NhbDwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MzwvQ29sdW5hPjxJbmljaW8+MTI8L0luaWNpbz48V" +
            "GFtYW5obz4zPC9UYW1hbmhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q29kaWdvQmFycmFWb2x1bWU8L" +
            "05vbWVBdHJpYnV0bz48Q29sdW5hPjQ8L0NvbHVuYT48SW5pY2lvPjE1PC9JbmljaW8+PFRhbWFuaG8+N" +
            "jwvVGFtYW5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+P" +
            "EZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPk5vbWU8L05vbWVBdHJpYnV0bz48Q29sdW5hP" +
            "jU8L0NvbHVuYT48SW5pY2lvPjIxPC9JbmljaW8+PFRhbWFuaG8+NDE8L1RhbWFuaG8+PERlbGltaXRhZ" +
            "G9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+R" +
            "W5kZXJlY288L05vbWVBdHJpYnV0bz48SW5pY2lvPjMwPC9JbmljaW8+PENvbHVuYT42PC9Db2x1bmE+P" +
            "FRhbWFuaG8+NDA8L1RhbWFuaG8+PERlbGltaXRhZG9yPjs8L0RlbGltaXRhZG9yPjwvRm9ybWF0YWNhb" +
            "1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5CYWlycm88L05vbWVBdHJpY" +
            "nV0bz48Q29sdW5hPjc8L0NvbHVuYT48SW5pY2lvPjEwMzwvSW5pY2lvPjxUYW1hbmhvPjE1PC9UYW1hb" +
            "mhvPjxEZWxpbWl0YWRvcj47PC9EZWxpbWl0YWRvcj48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q2lkYWRlPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT44PC9Db" +
            "2x1bmE+PEluaWNpbz4xMTk8L0luaWNpbz48VGFtYW5obz4xNTwvVGFtYW5obz48RGVsaW1pdGFkb3I+O" +
            "zwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZ" +
            "UF0cmlidXRvPlVGPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT45PC9Db2x1bmE+PEluaWNpbz43ODwvSW5pY" +
            "2lvPjxUYW1hbmhvPjI8L1RhbWFuaG8+PERlbGltaXRhZG9yPjs8L0RlbGltaXRhZG9yPjwvRm9ybWF0Y" +
            "WNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5DRVA8L05vbWVBdHJpY" +
            "nV0bz48Q29sdW5hPjEwPC9Db2x1bmE+PEluaWNpbz4xMzg8L0luaWNpbz48VGFtYW5obz4xMDwvVGFtY" +
            "W5obz48RGVsaW1pdGFkb3I+OzwvRGVsaW1pdGFkb3I+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hd" +
            "GFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPlJlZ2lzdHJvPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT4xM" +
            "TwvQ29sdW5hPjxJbmljaW8+MTQ5PC9JbmljaW8+PFRhbWFuaG8+MTM8L1RhbWFuaG8+PERlbGltaXRhZ" +
            "G9yLz48L0Zvcm1hdGFjYW9QbGFuaWxoYT48L0FycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+")]
        public string Layout {
            get {
                return ((string)(this["Layout"]));
            }
            set {
                this["Layout"] = value;
            }
        }
    }
}
