//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Visualset.IntegradorWebService.DataLayer/Connected Services/ServiceReference/Reference.cs
namespace Visualset.IntegradorWebService.DataLayer.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.visualset.inf.br/", ConfigurationName="ServiceReference.PostagemVippSoap")]
=======
namespace Visualset.IntegradorWebService.DataLayer.WebReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.visualset.inf.br/", ConfigurationName="WebReferences.PostagemVippSoap")]
>>>>>>> 9fa98c482e24165f3582d7135ebcb72f2fd7fb1b:Visualset.IntegradorWebService.DataLayer/Connected Services/WebReferences/Reference.cs
    public interface PostagemVippSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearObjetoCorreios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
<<<<<<< HEAD:Visualset.IntegradorWebService.DataLayer/Connected Services/ServiceReference/Reference.cs
        Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios([System.ServiceModel.MessageParameterAttribute(Name="BloquearObjetoCorreios")] Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearObjetoCorreios", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios> BloquearObjetoCorreiosAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearDownloadConhecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearDownloadConhecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload> BloquearDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/LiberarDownloadConhecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/LiberarDownloadConhecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload> LiberarDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/ListarRastreioObjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.ServiceReference.ObjetoRastreio[] ListarRastreioObjeto(Visualset.IntegradorWebService.DataLayer.ServiceReference.ListarRastreio ListarRastreio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/ListarRastreioObjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.ObjetoRastreio[]> ListarRastreioObjetoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.ListarRastreio ListarRastreio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PostarObjeto(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> PostarObjetoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjetoObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemRetorno PostarObjetoObject(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjetoObject", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemRetorno> PostarObjetoObjectAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/SolicitarEtiqueta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.ServiceReference.RetornoEtiquetas SolicitarEtiqueta(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/SolicitarEtiqueta", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.RetornoEtiquetas> SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade);
=======
        Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios([System.ServiceModel.MessageParameterAttribute(Name="BloquearObjetoCorreios")] Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearObjetoCorreios", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios> BloquearObjetoCorreiosAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearDownloadConhecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/BloquearDownloadConhecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload> BloquearDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/LiberarDownloadConhecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/LiberarDownloadConhecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload> LiberarDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarPostagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/ListarRastreioObjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.WebReferences.ObjetoRastreio[] ListarRastreioObjeto(Visualset.IntegradorWebService.DataLayer.WebReferences.ListarRastreio ListarRastreio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/ListarRastreioObjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.ObjetoRastreio[]> ListarRastreioObjetoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.ListarRastreio ListarRastreio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PostarObjeto(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> PostarObjetoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjetoObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemRetorno PostarObjetoObject(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/PostarObjetoObject", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemRetorno> PostarObjetoObjectAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/SolicitarEtiqueta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Visualset.IntegradorWebService.DataLayer.WebReferences.RetornoEtiquetas SolicitarEtiqueta(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.visualset.inf.br/SolicitarEtiqueta", ReplyAction="*")]
        System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.RetornoEtiquetas> SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade);
>>>>>>> 9fa98c482e24165f3582d7135ebcb72f2fd7fb1b:Visualset.IntegradorWebService.DataLayer/Connected Services/WebReferences/Reference.cs
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class BloquearObjetoCorreios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
                this.RaisePropertyChanged("Etiqueta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class PerfilVipp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string tokenField;
        
        private string idPerfilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
                this.RaisePropertyChanged("IdPerfil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class EtiquetaPostagem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroEtiquetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroEtiqueta {
            get {
                return this.numeroEtiquetaField;
            }
            set {
                this.numeroEtiquetaField = value;
                this.RaisePropertyChanged("NumeroEtiqueta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class RetornoEtiquetas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EtiquetaPostagem[] etiquetasField;
        
        private Erro[] listaErrosField;
        
        private StSolicitacao stSolicitacaoField;
        
        private string statusSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public EtiquetaPostagem[] Etiquetas {
            get {
                return this.etiquetasField;
            }
            set {
                this.etiquetasField = value;
                this.RaisePropertyChanged("Etiquetas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StSolicitacao StSolicitacao {
            get {
                return this.stSolicitacaoField;
            }
            set {
                this.stSolicitacaoField = value;
                this.RaisePropertyChanged("StSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StatusSolicitacao {
            get {
                return this.statusSolicitacaoField;
            }
            set {
                this.statusSolicitacaoField = value;
                this.RaisePropertyChanged("StatusSolicitacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Erro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoErro tipoErroField;
        
        private string atributoField;
        
        private string descricaoField;
        
        private string mensagemField;
        
        private string stackTraceField;
        
        private string stackTraceOutField;
        
        private string origemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TipoErro TipoErro {
            get {
                return this.tipoErroField;
            }
            set {
                this.tipoErroField = value;
                this.RaisePropertyChanged("TipoErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Atributo {
            get {
                return this.atributoField;
            }
            set {
                this.atributoField = value;
                this.RaisePropertyChanged("Atributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StackTraceOut {
            get {
                return this.stackTraceOutField;
            }
            set {
                this.stackTraceOutField = value;
                this.RaisePropertyChanged("StackTraceOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
                this.RaisePropertyChanged("Origem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public enum TipoErro {
        
        /// <remarks/>
        Excecao,
        
        /// <remarks/>
        RegraNegocio,
        
        /// <remarks/>
        Validacao,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public enum StSolicitacao {
        
        /// <remarks/>
        Invalida,
        
        /// <remarks/>
        Valida,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class PostagemRetorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private ContratoEct contratoEctField;
        
        private Destinatario destinatarioField;
        
        private Servico servicoField;
        
        private NotaFiscal[] notasFiscaisField;
        
        private VolumeObjeto[] volumesField;
        
        private Erro[] listaErrosField;
        
        private StSolicitacao stPostagemField;
        
        private int idStatusPostagemField;
        
        private string statusPostagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContratoEct ContratoEct {
            get {
                return this.contratoEctField;
            }
            set {
                this.contratoEctField = value;
                this.RaisePropertyChanged("ContratoEct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("Destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
                this.RaisePropertyChanged("Servico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public NotaFiscal[] NotasFiscais {
            get {
                return this.notasFiscaisField;
            }
            set {
                this.notasFiscaisField = value;
                this.RaisePropertyChanged("NotasFiscais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public VolumeObjeto[] Volumes {
            get {
                return this.volumesField;
            }
            set {
                this.volumesField = value;
                this.RaisePropertyChanged("Volumes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public StSolicitacao StPostagem {
            get {
                return this.stPostagemField;
            }
            set {
                this.stPostagemField = value;
                this.RaisePropertyChanged("StPostagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int IdStatusPostagem {
            get {
                return this.idStatusPostagemField;
            }
            set {
                this.idStatusPostagemField = value;
                this.RaisePropertyChanged("IdStatusPostagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StatusPostagem {
            get {
                return this.statusPostagemField;
            }
            set {
                this.statusPostagemField = value;
                this.RaisePropertyChanged("StatusPostagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ContratoEct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nrContratoField;
        
        private string codigoAdministrativoField;
        
        private string nrCartaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NrContrato {
            get {
                return this.nrContratoField;
            }
            set {
                this.nrContratoField = value;
                this.RaisePropertyChanged("NrContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoAdministrativo {
            get {
                return this.codigoAdministrativoField;
            }
            set {
                this.codigoAdministrativoField = value;
                this.RaisePropertyChanged("CodigoAdministrativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NrCartao {
            get {
                return this.nrCartaoField;
            }
            set {
                this.nrCartaoField = value;
                this.RaisePropertyChanged("NrCartao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Destinatario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjCpfField;
        
        private string ieRgField;
        
        private string nomeField;
        
        private string segundaLinhaDestinatarioField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string cepField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CnpjCpf {
            get {
                return this.cnpjCpfField;
            }
            set {
                this.cnpjCpfField = value;
                this.RaisePropertyChanged("CnpjCpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IeRg {
            get {
                return this.ieRgField;
            }
            set {
                this.ieRgField = value;
                this.RaisePropertyChanged("IeRg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SegundaLinhaDestinatario {
            get {
                return this.segundaLinhaDestinatarioField;
            }
            set {
                this.segundaLinhaDestinatarioField = value;
                this.RaisePropertyChanged("SegundaLinhaDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("Cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("Telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Servico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string servicoECTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServicoECT {
            get {
                return this.servicoECTField;
            }
            set {
                this.servicoECTField = value;
                this.RaisePropertyChanged("ServicoECT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class NotaFiscal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dtNotaFiscalField;
        
        private string serieNotaFiscalField;
        
        private string nrNotaFiscalField;
        
        private string vlrTotalNotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DtNotaFiscal {
            get {
                return this.dtNotaFiscalField;
            }
            set {
                this.dtNotaFiscalField = value;
                this.RaisePropertyChanged("DtNotaFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SerieNotaFiscal {
            get {
                return this.serieNotaFiscalField;
            }
            set {
                this.serieNotaFiscalField = value;
                this.RaisePropertyChanged("SerieNotaFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NrNotaFiscal {
            get {
                return this.nrNotaFiscalField;
            }
            set {
                this.nrNotaFiscalField = value;
                this.RaisePropertyChanged("NrNotaFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VlrTotalNota {
            get {
                return this.vlrTotalNotaField;
            }
            set {
                this.vlrTotalNotaField = value;
                this.RaisePropertyChanged("VlrTotalNota");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class VolumeObjeto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pesoField;
        
        private string alturaField;
        
        private string larguraField;
        
        private string comprimentoField;
        
        private string contaLoteField;
        
        private string chaveRoteamentoField;
        
        private string codigoBarraVolumeField;
        
        private string codigoBarraClienteField;
        
        private string observacaoVisualField;
        
        private string observacaoQuatroField;
        
        private string observacaoCincoField;
        
        private string posicaoVolumeField;
        
        private string conteudoField;
        
        private DeclaracaoConteudo declaracaoConteudoField;
        
        private string valorDeclaradoField;
        
        private string adicionaisVolumeField;
        
        private string vlrACobrarField;
        
        private string etiquetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("Peso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("Altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Largura {
            get {
                return this.larguraField;
            }
            set {
                this.larguraField = value;
                this.RaisePropertyChanged("Largura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comprimento {
            get {
                return this.comprimentoField;
            }
            set {
                this.comprimentoField = value;
                this.RaisePropertyChanged("Comprimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContaLote {
            get {
                return this.contaLoteField;
            }
            set {
                this.contaLoteField = value;
                this.RaisePropertyChanged("ContaLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ChaveRoteamento {
            get {
                return this.chaveRoteamentoField;
            }
            set {
                this.chaveRoteamentoField = value;
                this.RaisePropertyChanged("ChaveRoteamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CodigoBarraVolume {
            get {
                return this.codigoBarraVolumeField;
            }
            set {
                this.codigoBarraVolumeField = value;
                this.RaisePropertyChanged("CodigoBarraVolume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CodigoBarraCliente {
            get {
                return this.codigoBarraClienteField;
            }
            set {
                this.codigoBarraClienteField = value;
                this.RaisePropertyChanged("CodigoBarraCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ObservacaoVisual {
            get {
                return this.observacaoVisualField;
            }
            set {
                this.observacaoVisualField = value;
                this.RaisePropertyChanged("ObservacaoVisual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ObservacaoQuatro {
            get {
                return this.observacaoQuatroField;
            }
            set {
                this.observacaoQuatroField = value;
                this.RaisePropertyChanged("ObservacaoQuatro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ObservacaoCinco {
            get {
                return this.observacaoCincoField;
            }
            set {
                this.observacaoCincoField = value;
                this.RaisePropertyChanged("ObservacaoCinco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PosicaoVolume {
            get {
                return this.posicaoVolumeField;
            }
            set {
                this.posicaoVolumeField = value;
                this.RaisePropertyChanged("PosicaoVolume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Conteudo {
            get {
                return this.conteudoField;
            }
            set {
                this.conteudoField = value;
                this.RaisePropertyChanged("Conteudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public DeclaracaoConteudo DeclaracaoConteudo {
            get {
                return this.declaracaoConteudoField;
            }
            set {
                this.declaracaoConteudoField = value;
                this.RaisePropertyChanged("DeclaracaoConteudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ValorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
                this.RaisePropertyChanged("ValorDeclarado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AdicionaisVolume {
            get {
                return this.adicionaisVolumeField;
            }
            set {
                this.adicionaisVolumeField = value;
                this.RaisePropertyChanged("AdicionaisVolume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string VlrACobrar {
            get {
                return this.vlrACobrarField;
            }
            set {
                this.vlrACobrarField = value;
                this.RaisePropertyChanged("VlrACobrar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
                this.RaisePropertyChanged("Etiqueta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class DeclaracaoConteudo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoRemetenteField;
        
        private string documentoDestinatarioField;
        
        private int pesoTotalField;
        
        private ItemConteudo[] itemConteudoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentoRemetente {
            get {
                return this.documentoRemetenteField;
            }
            set {
                this.documentoRemetenteField = value;
                this.RaisePropertyChanged("DocumentoRemetente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentoDestinatario {
            get {
                return this.documentoDestinatarioField;
            }
            set {
                this.documentoDestinatarioField = value;
                this.RaisePropertyChanged("DocumentoDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PesoTotal {
            get {
                return this.pesoTotalField;
            }
            set {
                this.pesoTotalField = value;
                this.RaisePropertyChanged("PesoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ItemConteudo[] ItemConteudo {
            get {
                return this.itemConteudoField;
            }
            set {
                this.itemConteudoField = value;
                this.RaisePropertyChanged("ItemConteudo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ItemConteudo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descricaoConteudoField;
        
        private int quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DescricaoConteudo {
            get {
                return this.descricaoConteudoField;
            }
            set {
                this.descricaoConteudoField = value;
                this.RaisePropertyChanged("DescricaoConteudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("Quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
                this.RaisePropertyChanged("QuantidadeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class Postagem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private ContratoEct contratoEctField;
        
        private Destinatario destinatarioField;
        
        private Servico servicoField;
        
        private NotaFiscal[] notasFiscaisField;
        
        private VolumeObjeto[] volumesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContratoEct ContratoEct {
            get {
                return this.contratoEctField;
            }
            set {
                this.contratoEctField = value;
                this.RaisePropertyChanged("ContratoEct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("Destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
                this.RaisePropertyChanged("Servico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public NotaFiscal[] NotasFiscais {
            get {
                return this.notasFiscaisField;
            }
            set {
                this.notasFiscaisField = value;
                this.RaisePropertyChanged("NotasFiscais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public VolumeObjeto[] Volumes {
            get {
                return this.volumesField;
            }
            set {
                this.volumesField = value;
                this.RaisePropertyChanged("Volumes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class EventoRastreio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idVolumeObjetoField;
        
        private long idEventoRastreioField;
        
        private string tipoEventoField;
        
        private int idStatusField;
        
        private int idStatusEventoField;
        
        private string descricaoStatusEventoField;
        
        private System.DateTime dtEventoCompletaField;
        
        private int idGrupoStatusEventoField;
        
        private string nomeGrupoStatusEventoField;
        
        private string codigoEdiField;
        
        private long idLocalEventoOrigemField;
        
        private string localEventoField;
        
        private string tipoEnderecoField;
        
        private string enderecoEventoField;
        
        private string complementoEnderecoEventoField;
        
        private string bairroEventoField;
        
        private string cidadeEventoField;
        
        private string uFEventoField;
        
        private string sTOEventoField;
        
        private long idLocalEventoDestinoField;
        
        private string destinoField;
        
        private string tipoEnderecoDestinoField;
        
        private string enderecoDestinoField;
        
        private string complementoEnderecoDestinoField;
        
        private string bairroDestinoField;
        
        private string cidadeDestinoField;
        
        private string uFDestinoField;
        
        private string sTODestinoField;
        
        private string nomeRecebedorField;
        
        private string documentoRecebedorField;
        
        private string obsRecebedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdVolumeObjeto {
            get {
                return this.idVolumeObjetoField;
            }
            set {
                this.idVolumeObjetoField = value;
                this.RaisePropertyChanged("IdVolumeObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdEventoRastreio {
            get {
                return this.idEventoRastreioField;
            }
            set {
                this.idEventoRastreioField = value;
                this.RaisePropertyChanged("IdEventoRastreio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
                this.RaisePropertyChanged("TipoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
                this.RaisePropertyChanged("IdStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
                this.RaisePropertyChanged("IdStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DescricaoStatusEvento {
            get {
                return this.descricaoStatusEventoField;
            }
            set {
                this.descricaoStatusEventoField = value;
                this.RaisePropertyChanged("DescricaoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DtEventoCompleta {
            get {
                return this.dtEventoCompletaField;
            }
            set {
                this.dtEventoCompletaField = value;
                this.RaisePropertyChanged("DtEventoCompleta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IdGrupoStatusEvento {
            get {
                return this.idGrupoStatusEventoField;
            }
            set {
                this.idGrupoStatusEventoField = value;
                this.RaisePropertyChanged("IdGrupoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NomeGrupoStatusEvento {
            get {
                return this.nomeGrupoStatusEventoField;
            }
            set {
                this.nomeGrupoStatusEventoField = value;
                this.RaisePropertyChanged("NomeGrupoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CodigoEdi {
            get {
                return this.codigoEdiField;
            }
            set {
                this.codigoEdiField = value;
                this.RaisePropertyChanged("CodigoEdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long IdLocalEventoOrigem {
            get {
                return this.idLocalEventoOrigemField;
            }
            set {
                this.idLocalEventoOrigemField = value;
                this.RaisePropertyChanged("IdLocalEventoOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LocalEvento {
            get {
                return this.localEventoField;
            }
            set {
                this.localEventoField = value;
                this.RaisePropertyChanged("LocalEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TipoEndereco {
            get {
                return this.tipoEnderecoField;
            }
            set {
                this.tipoEnderecoField = value;
                this.RaisePropertyChanged("TipoEndereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string EnderecoEvento {
            get {
                return this.enderecoEventoField;
            }
            set {
                this.enderecoEventoField = value;
                this.RaisePropertyChanged("EnderecoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ComplementoEnderecoEvento {
            get {
                return this.complementoEnderecoEventoField;
            }
            set {
                this.complementoEnderecoEventoField = value;
                this.RaisePropertyChanged("ComplementoEnderecoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BairroEvento {
            get {
                return this.bairroEventoField;
            }
            set {
                this.bairroEventoField = value;
                this.RaisePropertyChanged("BairroEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CidadeEvento {
            get {
                return this.cidadeEventoField;
            }
            set {
                this.cidadeEventoField = value;
                this.RaisePropertyChanged("CidadeEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UFEvento {
            get {
                return this.uFEventoField;
            }
            set {
                this.uFEventoField = value;
                this.RaisePropertyChanged("UFEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string STOEvento {
            get {
                return this.sTOEventoField;
            }
            set {
                this.sTOEventoField = value;
                this.RaisePropertyChanged("STOEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long IdLocalEventoDestino {
            get {
                return this.idLocalEventoDestinoField;
            }
            set {
                this.idLocalEventoDestinoField = value;
                this.RaisePropertyChanged("IdLocalEventoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TipoEnderecoDestino {
            get {
                return this.tipoEnderecoDestinoField;
            }
            set {
                this.tipoEnderecoDestinoField = value;
                this.RaisePropertyChanged("TipoEnderecoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string EnderecoDestino {
            get {
                return this.enderecoDestinoField;
            }
            set {
                this.enderecoDestinoField = value;
                this.RaisePropertyChanged("EnderecoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ComplementoEnderecoDestino {
            get {
                return this.complementoEnderecoDestinoField;
            }
            set {
                this.complementoEnderecoDestinoField = value;
                this.RaisePropertyChanged("ComplementoEnderecoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BairroDestino {
            get {
                return this.bairroDestinoField;
            }
            set {
                this.bairroDestinoField = value;
                this.RaisePropertyChanged("BairroDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CidadeDestino {
            get {
                return this.cidadeDestinoField;
            }
            set {
                this.cidadeDestinoField = value;
                this.RaisePropertyChanged("CidadeDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string UFDestino {
            get {
                return this.uFDestinoField;
            }
            set {
                this.uFDestinoField = value;
                this.RaisePropertyChanged("UFDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string STODestino {
            get {
                return this.sTODestinoField;
            }
            set {
                this.sTODestinoField = value;
                this.RaisePropertyChanged("STODestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string NomeRecebedor {
            get {
                return this.nomeRecebedorField;
            }
            set {
                this.nomeRecebedorField = value;
                this.RaisePropertyChanged("NomeRecebedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DocumentoRecebedor {
            get {
                return this.documentoRecebedorField;
            }
            set {
                this.documentoRecebedorField = value;
                this.RaisePropertyChanged("DocumentoRecebedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ObsRecebedor {
            get {
                return this.obsRecebedorField;
            }
            set {
                this.obsRecebedorField = value;
                this.RaisePropertyChanged("ObsRecebedor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ObjetoRastreio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idConhecimentoField;
        
        private string etiquetaPostagemField;
        
        private System.DateTime dtPostagemField;
        
        private long idUltimoStatusField;
        
        private int idGrupoStatusEventoField;
        
        private string nomeGrupoStatusEventoField;
        
        private long idStatusEntregaField;
        
        private short stPIField;
        
        private long idAoRemetenteField;
        
        private int stConhecimentoField;
        
        private EventoRastreio[] eventoRastreioField;
        
        private string statusSolicitacaoField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdConhecimento {
            get {
                return this.idConhecimentoField;
            }
            set {
                this.idConhecimentoField = value;
                this.RaisePropertyChanged("IdConhecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EtiquetaPostagem {
            get {
                return this.etiquetaPostagemField;
            }
            set {
                this.etiquetaPostagemField = value;
                this.RaisePropertyChanged("EtiquetaPostagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DtPostagem {
            get {
                return this.dtPostagemField;
            }
            set {
                this.dtPostagemField = value;
                this.RaisePropertyChanged("DtPostagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long IdUltimoStatus {
            get {
                return this.idUltimoStatusField;
            }
            set {
                this.idUltimoStatusField = value;
                this.RaisePropertyChanged("IdUltimoStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdGrupoStatusEvento {
            get {
                return this.idGrupoStatusEventoField;
            }
            set {
                this.idGrupoStatusEventoField = value;
                this.RaisePropertyChanged("IdGrupoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NomeGrupoStatusEvento {
            get {
                return this.nomeGrupoStatusEventoField;
            }
            set {
                this.nomeGrupoStatusEventoField = value;
                this.RaisePropertyChanged("NomeGrupoStatusEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long IdStatusEntrega {
            get {
                return this.idStatusEntregaField;
            }
            set {
                this.idStatusEntregaField = value;
                this.RaisePropertyChanged("IdStatusEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public short StPI {
            get {
                return this.stPIField;
            }
            set {
                this.stPIField = value;
                this.RaisePropertyChanged("StPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long IdAoRemetente {
            get {
                return this.idAoRemetenteField;
            }
            set {
                this.idAoRemetenteField = value;
                this.RaisePropertyChanged("IdAoRemetente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int StConhecimento {
            get {
                return this.stConhecimentoField;
            }
            set {
                this.stConhecimentoField = value;
                this.RaisePropertyChanged("StConhecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public EventoRastreio[] EventoRastreio {
            get {
                return this.eventoRastreioField;
            }
            set {
                this.eventoRastreioField = value;
                this.RaisePropertyChanged("EventoRastreio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string StatusSolicitacao {
            get {
                return this.statusSolicitacaoField;
            }
            set {
                this.statusSolicitacaoField = value;
                this.RaisePropertyChanged("StatusSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class ListarRastreio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private string nrEtiquetaPostagemField;
        
        private string idConhecimentoField;
        
        private string observacaoUmField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NrEtiquetaPostagem {
            get {
                return this.nrEtiquetaPostagemField;
            }
            set {
                this.nrEtiquetaPostagemField = value;
                this.RaisePropertyChanged("NrEtiquetaPostagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdConhecimento {
            get {
                return this.idConhecimentoField;
            }
            set {
                this.idConhecimentoField = value;
                this.RaisePropertyChanged("IdConhecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ObservacaoUm {
            get {
                return this.observacaoUmField;
            }
            set {
                this.observacaoUmField = value;
                this.RaisePropertyChanged("ObservacaoUm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class LiberarDownload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private Erro[] listaErrosField;
        
        private short stLiberadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
                this.RaisePropertyChanged("Etiqueta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short StLiberado {
            get {
                return this.stLiberadoField;
            }
            set {
                this.stLiberadoField = value;
                this.RaisePropertyChanged("StLiberado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.visualset.inf.br/")]
    public partial class BloquearDownload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilVipp perfilVippField;
        
        private string etiquetaField;
        
        private short stBloqueadoField;
        
        private string descricaoField;
        
        private Erro[] listaErrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilVipp PerfilVipp {
            get {
                return this.perfilVippField;
            }
            set {
                this.perfilVippField = value;
                this.RaisePropertyChanged("PerfilVipp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
                this.RaisePropertyChanged("Etiqueta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short StBloqueado {
            get {
                return this.stBloqueadoField;
            }
            set {
                this.stBloqueadoField = value;
                this.RaisePropertyChanged("StBloqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Erro[] ListaErros {
            get {
                return this.listaErrosField;
            }
            set {
                this.listaErrosField = value;
                this.RaisePropertyChanged("ListaErros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
<<<<<<< HEAD:Visualset.IntegradorWebService.DataLayer/Connected Services/ServiceReference/Reference.cs
    public interface PostagemVippSoapChannel : Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemVippSoap, System.ServiceModel.IClientChannel {
=======
    public interface PostagemVippSoapChannel : Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemVippSoap, System.ServiceModel.IClientChannel {
>>>>>>> 9fa98c482e24165f3582d7135ebcb72f2fd7fb1b:Visualset.IntegradorWebService.DataLayer/Connected Services/WebReferences/Reference.cs
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
<<<<<<< HEAD:Visualset.IntegradorWebService.DataLayer/Connected Services/ServiceReference/Reference.cs
    public partial class PostagemVippSoapClient : System.ServiceModel.ClientBase<Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemVippSoap>, Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemVippSoap {
=======
    public partial class PostagemVippSoapClient : System.ServiceModel.ClientBase<Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemVippSoap>, Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemVippSoap {
>>>>>>> 9fa98c482e24165f3582d7135ebcb72f2fd7fb1b:Visualset.IntegradorWebService.DataLayer/Connected Services/WebReferences/Reference.cs
        
        public PostagemVippSoapClient() {
        }
        
        public PostagemVippSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostagemVippSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostagemVippSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostagemVippSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
<<<<<<< HEAD:Visualset.IntegradorWebService.DataLayer/Connected Services/ServiceReference/Reference.cs
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios1) {
            return base.Channel.BloquearObjetoCorreios(BloquearObjetoCorreios1);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios> BloquearObjetoCorreiosAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearObjetoCorreios BloquearObjetoCorreios) {
            return base.Channel.BloquearObjetoCorreiosAsync(BloquearObjetoCorreios);
        }
        
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearPostagem) {
            return base.Channel.BloquearDownloadConhecimento(BloquearPostagem);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload> BloquearDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.BloquearDownload BloquearPostagem) {
            return base.Channel.BloquearDownloadConhecimentoAsync(BloquearPostagem);
        }
        
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarPostagem) {
            return base.Channel.LiberarDownloadConhecimento(LiberarPostagem);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload> LiberarDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.LiberarDownload LiberarPostagem) {
            return base.Channel.LiberarDownloadConhecimentoAsync(LiberarPostagem);
        }
        
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.ObjetoRastreio[] ListarRastreioObjeto(Visualset.IntegradorWebService.DataLayer.ServiceReference.ListarRastreio ListarRastreio) {
            return base.Channel.ListarRastreioObjeto(ListarRastreio);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.ObjetoRastreio[]> ListarRastreioObjetoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.ListarRastreio ListarRastreio) {
            return base.Channel.ListarRastreioObjetoAsync(ListarRastreio);
        }
        
        public System.Xml.XmlNode PostarObjeto(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp) {
            return base.Channel.PostarObjeto(PostagemVipp);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> PostarObjetoAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoAsync(PostagemVipp);
        }
        
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemRetorno PostarObjetoObject(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoObject(PostagemVipp);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.PostagemRetorno> PostarObjetoObjectAsync(Visualset.IntegradorWebService.DataLayer.ServiceReference.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoObjectAsync(PostagemVipp);
        }
        
        public Visualset.IntegradorWebService.DataLayer.ServiceReference.RetornoEtiquetas SolicitarEtiqueta(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
            return base.Channel.SolicitarEtiqueta(NumeroCartao, Usuario, Senha, CodigoServico, Quantidade);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.ServiceReference.RetornoEtiquetas> SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
=======
        public Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios1) {
            return base.Channel.BloquearObjetoCorreios(BloquearObjetoCorreios1);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios> BloquearObjetoCorreiosAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearObjetoCorreios BloquearObjetoCorreios) {
            return base.Channel.BloquearObjetoCorreiosAsync(BloquearObjetoCorreios);
        }
        
        public Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearPostagem) {
            return base.Channel.BloquearDownloadConhecimento(BloquearPostagem);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload> BloquearDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.BloquearDownload BloquearPostagem) {
            return base.Channel.BloquearDownloadConhecimentoAsync(BloquearPostagem);
        }
        
        public Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarDownloadConhecimento(Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarPostagem) {
            return base.Channel.LiberarDownloadConhecimento(LiberarPostagem);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload> LiberarDownloadConhecimentoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.LiberarDownload LiberarPostagem) {
            return base.Channel.LiberarDownloadConhecimentoAsync(LiberarPostagem);
        }
        
        public Visualset.IntegradorWebService.DataLayer.WebReferences.ObjetoRastreio[] ListarRastreioObjeto(Visualset.IntegradorWebService.DataLayer.WebReferences.ListarRastreio ListarRastreio) {
            return base.Channel.ListarRastreioObjeto(ListarRastreio);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.ObjetoRastreio[]> ListarRastreioObjetoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.ListarRastreio ListarRastreio) {
            return base.Channel.ListarRastreioObjetoAsync(ListarRastreio);
        }
        
        public System.Xml.XmlNode PostarObjeto(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp) {
            return base.Channel.PostarObjeto(PostagemVipp);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> PostarObjetoAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoAsync(PostagemVipp);
        }
        
        public Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemRetorno PostarObjetoObject(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoObject(PostagemVipp);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.PostagemRetorno> PostarObjetoObjectAsync(Visualset.IntegradorWebService.DataLayer.WebReferences.Postagem PostagemVipp) {
            return base.Channel.PostarObjetoObjectAsync(PostagemVipp);
        }
        
        public Visualset.IntegradorWebService.DataLayer.WebReferences.RetornoEtiquetas SolicitarEtiqueta(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
            return base.Channel.SolicitarEtiqueta(NumeroCartao, Usuario, Senha, CodigoServico, Quantidade);
        }
        
        public System.Threading.Tasks.Task<Visualset.IntegradorWebService.DataLayer.WebReferences.RetornoEtiquetas> SolicitarEtiquetaAsync(string NumeroCartao, string Usuario, string Senha, string CodigoServico, string Quantidade) {
>>>>>>> 9fa98c482e24165f3582d7135ebcb72f2fd7fb1b:Visualset.IntegradorWebService.DataLayer/Connected Services/WebReferences/Reference.cs
            return base.Channel.SolicitarEtiquetaAsync(NumeroCartao, Usuario, Senha, CodigoServico, Quantidade);
        }
    }
}
